Refactoring.

diff --git a/bin/complete-shell b/bin/complete-shell
--- a/bin/complete-shell
+++ b/bin/complete-shell
@@ -3,15 +3,10 @@
 die() { echo "$@" >&2; exit 1; }
 
 main() {
-  [[ -n "$COMPLETE_SHELL_ROOT" && -d "$COMPLETE_SHELL_ROOT" ]] ||
-    die "complete-shell not properly activated"
-  [[ $# == 2 &&
-     $1 =~ ^add$ &&
-     -f $2 &&
-     $2 =~ \.bash$
-  ]] || die "Usage complete-shell add <file.bash>"
+  check-env
+  get-opts "$@"
 
-  complete-shell:add "$2"
+  "complete-shell:$command_name" "${command_args[@]}"
 }
 
 complete-shell:add() {
@@ -25,6 +20,43 @@ complete-shell:add() {
   local name="${BASH_REMATCH[1]}"
   git config -f "$COMPLETE_SHELL_ROOT/config" \
     "complete-shell.$name" "$file"
+  complete-shell:rehash
+}
+
+complete-shell:install() {
+  local target="$1"
+  [[ $target =~ ^([-_a-zA-Z0-9]+)/([-_a-zA-Z0-9]+)$ ]] ||
+    die "Invalid install target '$target'"
+  local dir="${BASH_REMATCH[2]}"
+  [[ $dir =~ ^complete-([-_a-zA-Z0-9]+)$ ]] ||
+    die "Invalid complete-shell repo name: '$dir'"
+  local cmd_name="${BASH_REMATCH[1]}"
+  local repo_path="$COMPLETE_SHELL_ROOT/source/$dir"
+  git clone "https://github.com/$target" "$repo_path"
+  complete-shell:add "$repo_path/complete-$cmd_name.bash"
+}
+
+complete-shell:rehash() {
+  local all=(
+    $(git config -f $COMPLETE_SHELL_ROOT/config --get-regexp complete-shell)
+  )
+  set -- "${all[@]}"
+  while [[ $# -gt 0 ]]; do
+    local cmd_name="${1#complete-shell.}" bash_file="$2"
+    shift; shift
+    source $bash_file || continue
+    complete -F complete-shell:add-completion "$cmd_name"
+  done
+}
+
+check-env() {
+  [[ -n "$COMPLETE_SHELL_ROOT" && -d "$COMPLETE_SHELL_ROOT" ]] ||
+    die "complete-shell not properly activated"
+}
+
+get-opts() {
+  command_name="$1"; shift
+  command_args=("$@")
 }
 
 [[ $0 != $BASH_SOURCE ]] || main "$@"
